# Deploy the web application
# into the vercel as production
#
# ***** NOTE ******
# This deployment need to setup some secrets

name: Publish docs

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_WEB_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_PROJECT_ID }}

on:
  push:
    branches:
      - main
    paths:
      - "apps/docs/**"

jobs:
  deploy-to-vercel:
    name: Deploy to vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6

      - name: Setup bun environment
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install vercel cli
        run: bun add --global vercel@latest

      - name: Pull vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build project artifacts
        run: NITRO_PRESET=vercel vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy project artifacts to vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
